### ISSUE TITLE
make: Nothing to be done for 'deploy'

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/managed-node-metadata-operator#47]
I followed https://github.com/openshift/managed-node-metadata-operator/blob/main/docs/development-and-testing.md#deploy-to-cluster, but got the below error. Am I missing something? Thanks!
And, one more question, if I want to deploy it via the OLM, which command I should run? Thanks!
```console
[cloud-user@preserve-olm-env2 managed-node-metadata-operator]$ make deploy
make: Nothing to be done for 'deploy'.
```

**Comment by iamkirkbater** [comment]
👋🏼  Hi @jianzhangbjz!  Thanks for reporting this.

It looks like our makefile got refactored and we missed the docs update here.  Sorry about that!  Let me get back to you as soon as possible with the updated commands!
